# モデルパラメータ
model:
  # LightGBM設定
  lgbm:
    objective: binary
    metric: binary_logloss
    boosting_type: gbdt
    learning_rate: 0.05
    num_leaves: 31
    max_depth: -1
    feature_fraction: 0.9
    bagging_fraction: 0.8
    bagging_freq: 5
    verbose: -1
    random_state: 42

  learning_control:
    num_boost_round: 1000
    early_stopping_rounds: 50


# 閾値設定
threshold:
  optimal: 0.5078
  search_range:
    start: 0.3
    end: 0.7
    step: 0.001


# 実験管理、実験前に書き換える
experiment:
  name: lgbm_cvmean
  version: 1
  description: "LightGBM CV mean"
  tags:
    - lgbm
    - cv
    - feature_engineering
  author: shosei
